DROP TABLE IF EXISTS metadata;
CREATE TABLE metadata (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    capacity INTEGER NOT NULL,
    velocity INTEGER NOT NULL
);

DROP TABLE IF EXISTS consumption;
CREATE TABLE consumption (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    consumption INTEGER NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    cutoff DATE NOT NULL
);